[
"AAFeatureAR5WalletNative",
"AAFeatureAR5PromotionsNative",
"AAFeatureNew500MileUpgradesUI",
"AAFeatureDREligibilityService",
"AAFeatureAppShortcutsEnabled",
"AAFeatureDeniedBoarding",
"AAFeatureSSOAppSpinner",
"AAFeatureAirshipIntegration",
"AAFeatureCloudLogin",
"AAFeatureCloudLoginProtection",
"AAFeatureFlifoHighSpeedWifiAndPower-Android",
"AAFeaturePaymentManager"
]